# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix (-M is the "Meta" key, often the Alt key in Windows)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# start with window 1 (instead of 0)
set -g base-index 1

# start with pane 1 (instead of 0)
set -g pane-base-index 1

# set default terminal mode to 256 colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
